### ISSUE TITLE
RSS or Atom feeds

### ISSUE THREAD

**Issue by ckruse** [myfreeweb/sweetroll#1]
RSS or Atom feeds would be nice, so I could follow via feed reader

**Comment by myfreeweb** [comment]
That's already on the TODO list in the README! Well… there's a lot of stuff on the TODO list :D

**Comment by ckruse** [comment]
Yeah, I know, but I thought you will less likely forget it when I create an issue ;-)

**Comment by myfreeweb** [comment]
I haven't forgotten anything… I just don't have enough time/motivation for all the things…

**Comment by ckruse** [comment]
Sorry, just was teasing. I totally know the lack of time.

**Comment by myfreeweb** [comment]
You don't have to say "sorry" so much!

**Comment by myfreeweb** [comment]
Done! You can try following the feed with your old and boring (no microformats support) reader :D

**Comment by ckruse** [comment]
Cool!
