### ISSUE TITLE
[onboarding] let Stack fetch dependencies from GitHub?

### ISSUE THREAD

**Issue by hotzeplotz** [myfreeweb/sweetroll#4]
This is very minor, but i'm somewhat obsessed with onboarding: the current `stack.yaml` references local clones of your own Haskell libraries - this only a few seconds and can be scripted, but may be further streamlined outside of development.

I imagine the local clones are used in your own development workflow. However, would it be useful for me to send a PR that keeps the current `stack.yaml` with an alternative name (say `stack-development.yaml`) and updates `stack.yaml` to fetch these packages directly from GitHub?

This way, you (and others hacking locally on sweetroll, gitson, etc.) can still iterate quickly (`stack --stack-yaml stack-development.yaml build`) whereas new users checking out sweetroll can just issue `stack build` and let Stack do all the fetching etc.

(I see that your Indieweb libraries are on Hackage too, but it seems that only the GitHub master branches have all the latest features needed for master *sweetroll*, so it's probably best not to just let Stack fetch these from Hackage as Cabal dependencies for the time being)

I may be off with my proposed solution (just starting out with Haskell/Stack etc.) - it works for me but i may be very well overcomplicating 😐

**Comment by myfreeweb** [comment]
Yes, I have thought about alternative stack files, this is exactly the right solution, I've just been too lazy to do it :D Make the name shorter though: `stack-dev.yaml`

**Comment by hotzeplotz** [comment]
cool - PR on its way.
