### ISSUE TITLE
RSS/Atom feed

### ISSUE THREAD

**Issue by wezm** [myfreeweb/sweetroll#6]
> TODO
> 
> >   * frontend
> >       * bring back the atom feed

I know it's on the TODO list but would just like to add a +1 for being able to subscribe to your posts in my feed reader. 😃

**Comment by myfreeweb** [comment]
Well, you can subscribe to https://granary-demo.appspot.com/url?input=html&output=atom&url=https://unrelenting.technology :) I'll just add a `<link>` to that probably

**Comment by myfreeweb** [comment]
Added links to Atom, ActivityStreams 2.0 and JSON Feed :)

**Comment by wezm** [comment]
Awesome, thanks. Subscribed.
